### ISSUE TITLE
อยากให้เล่นตามเวลาที่กำหนด

### ISSUE THREAD

**Issue by rootEnginear** [riflowth/tier-discord-bot#15]
ลิงก์ Youtube บางทีจะมีเวลาติดมาด้วย เช่น https://youtu.be/fIKwmiN5btg?t=204
อยากให้เริ่มเล่นตรง t เลย

**Comment by riflowth** [comment]
This ticket has resolved the issue in this commit 992eb858ad235ecf16fb228eeec4d4baafba0a3b
